runtime: nodejs
service: rpc-proxy
env: flex
runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "22"
instance_class: F1


automatic_scaling:
  cpu_utilization:
    target_utilization: 0.75
  min_num_instances: 1
  max_num_instances: 5
  max_concurrent_requests: 500
  
handlers:
  - url: /.*
    redirect_http_response_code: 301
    script: auto

# Env vars are injected by deploy.sh
# env_variables:
#   LOCAL_NODE: $LOCAL_NODE
#   MEV_NODE: $MEV_NODE

